version: "3.8"

services:
  apache:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
        - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"